config/routes.rb
Studdy::Application.routes.draw do
  root 'about#index'
  get "about", to: 'about#index'
  devise_for :users
  resources :subtopics
  resources :topics
  resources :listings
  resources :users, only: [:show]
  resources :notifications, only: [:create]
end

app/models/availability.rb
class Availability < ActiveRecord::Base
	has_many :days
	belongs_to :listing
end

app/models/day.rb
class Day < ActiveRecord::Base
	belongs_to :availability
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	scope :recent, -> { where('created_at >= ?', Date.today - 30) }
	has_many :notifications
	belongs_to :user
	belongs_to :subtopic
	geocoded_by :address
	validates :title, :subtopic_id, :description, presence: :true
	validates :title, length: { in: 10..100 } 
	validates :description, length: { in: 10..1000 }
	validates :address, presence: :true, if: :in_person?
	validates :meeting_type, inclusion:  { 	in: ["In-person", "Virtual", "Both"] }
	after_validation :geocode, :if => :address_changed?

	def in_person?
		meeting_type == 'In-person' || meeting_type == 'Both'
	end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :listing
	belongs_to :user
end

app/models/subtopic.rb
class Subtopic < ActiveRecord::Base
	has_many :listings
	belongs_to :topic


	def self.search_for(query)
		where('name ILIKE :query', query: "%#{query}%")
	end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :subtopics
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  geocoded_by :zip_code
  validates :zip_code, presence: :true
  validates :zip_code, :numericality => { only_integer: true }
  validates :zip_code, length: { is: 5 }
  validates :name, presence: true
  validates :name, length: { maximum: 50 }
  after_validation :geocode, :if => :zip_code_changed?
  has_many :listings
  has_many :notifications, through: :listings
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :zip_code
  	devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
  	@listings = Listing.order(created_at: :asc)
  end

  def show
  	@listing = Listing.find params[:id]
    @user = @listing.user
  end

  def new 
  	@listing = Listing.new
    @subtopics = Subtopic.all
    @user_zip_code = current_user.zip_code
    @meeting_types = ["In-person", "Virtual", "Both"]
  end

  def create
    if user_signed_in? 
      safe_listing = params.require(:listing).permit(:title, :description, :subtopic_id, :meeting_type, :address, :latitude, :longitude).merge(user_id: current_user.id)
      @listing = Listing.create safe_listing
      @subtopics = Subtopic.all
      @user_zip_code = current_user.zip_code
      @meeting_types = ["In-person", "Virtual", "Both"]
      @listing.save ? redirect_to(@listing) : render("new")
    else
      redirect_to new_user_session_path, alert: "Only logged in users can create listings." 
    end
  end

  def edit
    @listing = Listing.find params[:id]
    @subtopics = Subtopic.all
    @user_zip_code = current_user.zip_code
    if current_user != @listing.user
      flash[:alert] = "You are not authorized to execute this action"
      redirect_to root_path
    end
  end

  def update
    @listing = Listing.find params[:id]
    safe_listing = params.require(:listing).permit(:title, :description, :subtopic_id, :meeting_type, :address, :latitude, :longitude).merge(user_id: @listing.user.id)
    @listing.update safe_listing
    redirect_to @listing
  end
  def destroy
      @listing = (Listing.find params[:id])
    if current_user == @listing.user
      @listing.destroy
      flash[:alert] = "Successully deleted listing"
      redirect_to root_path
    else 
      flash[:alert] = "You are not authorized to execute this action"
      redirect_to root_path
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

# how to send a message that the message was sent?
	def create
		if user_signed_in? 
			@user = current_user
			@listing_id = params[:listing_id]
			@notification = Notification.create(user_id: @user.id, listing_id: @listing_id)
			respond_to do |format|
				if @notification.save 
					UserMailer.notification_email(@listing_id, @user, @notification).deliver
					format.html { redirect_to(listing_path(@listing_id), notice: 'Notification sent!') }
					format.json { render json: listing_path(@listing_id), status: :created, location: listing_path(@listing) }
				else
					format.html { redirect_to(listing_path(@listing_id), notice: 'There was an error in sending your notification')  }
					format.json { render json: @notification.errors, status: :unprocessable_entity }
				end
			end
		else 
			redirect_to new_user_session_path, alert: "Only logged in users can connect with other users"
		end
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	
end

app/controllers/subtopics_controller.rb
class SubtopicsController < ApplicationController
  def index
    @subtopics = params[:q] ? Subtopic.search_for(params[:q]) : Subtopic.all
    if @subtopics.empty? 
       flash[:notice] = "No topics found using the keyword '#{params[:q]}.' Try again or refer to the list."
       redirect_to topics_path
    end
  end

  def new
    @subtopic = Subtopic.new 
  end

  def create
    safe_subtopic = params.require(:subtopic).require(:name, :topic_id)
    @subtopic = safe_subtopic.create(safe_subtopic)
    redirect to @subtopic
  end

  def show
    @subtopic = Subtopic.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def contact
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics =Topic.all
  end
  
  def new
    @topic = Topic.new 
  end

  def create
    safe_topic = params.require(:topic).permit(:name)
    @topic = Topic.create safe_topic
    redirect_to @topic 
  end

  def show
    @topic = Topic.find params[:id]
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find params[:id]
		@recent_listings = @user.listings.all
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subtopics_helper.rb
module SubtopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
	<% if @listing.errors.any? %>
	<div id="error_explanation">
			<h2><%= pluralize(@listing.errors.count, "error") %> have prevented this listing from saving:</h2>
			<ul>
			<% @listing.errors.full_messages.each do|msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
	</div>
	<% end %>
  <div class="form-group">
  	<%= f.input :title %>
  </div>
  <div class="form-group">
  	<%= f.input :description, as: :text %>
  	<%= f.association :subtopic, label: 'Topic', as: :select, collection: @subtopics %>
		<%= f.input :address, input_html: { value: @user_zip_code}  %>
	</div>	
	<div class="checkboxes">
		<%= f.input :meeting_type, collection: ["In-person", "Virtual", "Both"], as: :radio_buttons%>
	</div>
	<div class="form-actions">
		<%= f.button :submit %>
	</div>
<% end %>

app/views/listings/_listing.html.erb
<p><h1><%= @listing.title %></h1></p>
<p><%= @listing.description %></p>

<p><h4>Posted by: <%= link_to "#{@user.name}", user_path(@user.id)%></h4></p>

app/views/listings/edit.html.erb
<h2>Edit:</h2>
<%= render 'form' %>

app/views/listings/index.html.erb
<% @listings.each do |listing| %>
<div><%= link_to "#{listing.title}", listing_path(listing.id) %></div><hr>
<% end %>

app/views/listings/new.html.erb
<%= render 'form' %>

app/views/listings/show.html.erb
<div class="page">
<% if current_user == @user %> 
	<%= link_to "Edit listing", edit_listing_path %> | <%= link_to "Delete listing",  listing_path, method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>
<%= render @listing %>
<!-- <button class="btn btn-primary" type="button">Express interest</button> -->
<%= button_to "Express interest", notifications_path(listing_id: @listing.id), method: :post, confirm: "An email will be sent to #{@listing.user.name} notifying them of your interest. Are you sure?" %>
</div>

app/views/subtopics/create.html.erb
<h1>Subtopic#create</h1>
<p>Find me in app/views/subtopic/create.html.erb</p>

app/views/subtopics/destroy.html.erb
<h1>Subtopic#destroy</h1>
<p>Find me in app/views/subtopic/destroy.html.erb</p>

app/views/subtopics/edit.html.erb
<h1>Subtopic#edit</h1>
<p>Find me in app/views/subtopic/edit.html.erb</p>

app/views/subtopics/index.html.erb
<div class="page"><h2>Your Topic Search Results:</h2>

<% if @subtopics %>
	<% @subtopics.each do |subtopic| %>
		<p><%= link_to "#{subtopic.name}", subtopic_path(subtopic.id) %></p><hr>
	<% end %>
<% end %> 
</div>

app/views/subtopics/new.html.erb
<h1>Subtopic#new</h1>
<p>Find me in app/views/subtopic/new.html.erb</p>

app/views/subtopics/show.html.erb
<h2>Listings for <%= @subtopic.name %></h2>
<% @subtopic.listings.order(created_at: :desc).each do |listing| %>
		<%= link_to "#{listing.title}", listing_path(listing.id) %><hr>
<% end %>

app/views/subtopics/update.html.erb
<h1>Subtopic#update</h1>
<p>Find me in app/views/subtopic/update.html.erb</p>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

app/views/topics/index.html.erb
<div class="page">
<%= form_tag '/subtopics', method: :get do %>
<center> 
	<%= search_field_tag :q, params[:q], placeholder: "Search for a topic" %>
	<%= submit_tag "Search", name: nil %> 
<% end %>
<div class="notice"><%= flash[:notice] %>
</div>
<% @topics.each do |topic| %>
	<div><h1><%= topic.name %></h1></div>
		<% topic.subtopics.each do |subtopic| %>
				<div><h4><%= link_to "#{subtopic.name}", subtopic_path(subtopic.id) %></li></h4><hr></div>
		<% end %> 
<% end %>
</div>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/users/_listings_box.html.erb
<div class="span3">
	<table class="table table-hover">	
<% @user.listings.each do |listing| %>
	<th><%= link_to "#{listing.title}", listing_path(listing.id) %> <% if current_user == @user %>    
		<%= link_to "Edit", edit_listing_path %> | <%= link_to "Delete",  listing_path, method: :delete, data: {confirm: 'Are you sure?'} %> <% end %></th></tr>
<% end %>
	</table>
</div>

app/views/users/show.html.erb
<div class="page">
	<h1><%= @user.name %></h1>
	<p><%= @user.about %></p>

	<h2>Recent Listings:</h2>

	<% if @user.listings.empty? %>
		<big>No listings posted yet.</big>
	<% else %>
		<%= render 'listings_box' %>
	<% end %>

	<% if current_user == @user %>
		<h2>Your notifications:</h2>
		<div class="span3">
			<table class="table table-hover">
					<% if @user.listings.empty? %>
							<big>Create a listing to start receiving notifications.</big>
						<% end %>

					<% @user.listings.each do |listing| %>
						<th><%= link_to "#{listing.title}", listing_path(listing.id) %></th>
					<% if listing.notifications.empty? %>
					<ul><i>No notifications</i></ul>
					<% else %>
						<% listing.notifications.each do |notification| %>
							<div><ul><i><%= link_to "#{notification.user.name} is interested.", user_path(notification.user.id) %></i></ul></div>
						<% end %>
					<% end %>
				<% end %>
			</table>
	<% end %>
</div>